const { DatabaseSync } = require('node:sqlite');
const fs = require('fs');

const db = new DatabaseSync('database/tradeprodb.sqlite');
const tables = db.prepare(`SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'`).all();

let sqlScript = `-- SQL Server Schema Migration for TradePro ERP\n`;
sqlScript += `-- Generated automatically\n\n`;

let totalTables = 0;
let totalFks = 0;
let totalIndexes = 0;
let missing = [];

function getLongTextColumns() {
    return ['notes', 'description', 'details', 'permissions', 'address', 'company_address', 'reason'];
}

for (const table of tables) {
    totalTables++;
    const tableName = table.name;
    
    // Start idempotent block for table
    sqlScript += `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[${tableName}]') AND type in (N'U'))\nBEGIN\n`;
    sqlScript += `    CREATE TABLE [dbo].[${tableName}] (\n`;
    
    const columns = db.prepare(`PRAGMA table_info(${tableName})`).all();
    const fks = db.prepare(`PRAGMA foreign_key_list(${tableName})`).all();
    const indexes = db.prepare(`PRAGMA index_list(${tableName})`).all();
    
    // Parse the original CREATE TABLE to extract UNIQUE constraints
    const originalSql = table.sql;
    const isAutoIncrement = originalSql.includes('AUTOINCREMENT');
    
    let colDefs = [];
    for (const col of columns) {
        let def = `        [${col.name}] `;
        
        let sqlServerType = '';
        const typeUpper = (col.type || '').toUpperCase();
        
        if (typeUpper.includes('INT')) {
            sqlServerType = 'INT';
        } else if (typeUpper.includes('REAL') || typeUpper.includes('FLOAT') || typeUpper.includes('DOUBLE')) {
            sqlServerType = 'DECIMAL(18,4)';
        } else if (typeUpper.includes('TEXT') || typeUpper.includes('VARCHAR') || typeUpper === '') {
            // Intelligent NVARCHAR sizing
            if (getLongTextColumns().includes(col.name.toLowerCase())) {
                sqlServerType = 'NVARCHAR(MAX)';
            } else {
                sqlServerType = 'NVARCHAR(255)';
            }
        } else {
            sqlServerType = 'NVARCHAR(255)'; // Fallback
        }
        
        def += sqlServerType;
        
        if (col.pk) {
            if (isAutoIncrement && typeUpper.includes('INT')) {
                def += ' IDENTITY(1,1) PRIMARY KEY';
            } else {
                def += ' PRIMARY KEY';
            }
        }
        
        if (col.notnull && !col.pk) {
            def += ' NOT NULL';
        }
        
        // UNIQUE constraint parsing (SQLite PRAGMA doesn't show UNIQUE easily, we check original SQL)
        const colRegex = new RegExp(`\\b${col.name}\\b[^,]+UNIQUE`, 'i');
        if (colRegex.test(originalSql) && !col.pk) {
            def += ' UNIQUE';
        }
        
        if (col.dflt_value !== null) {
            let defaultVal = col.dflt_value;
            // Fix double quotes
            if (defaultVal.startsWith('"') && defaultVal.endsWith('"')) {
                defaultVal = "'" + defaultVal.substring(1, defaultVal.length - 1) + "'";
            }
            if (defaultVal.toLowerCase().includes("datetime('now'")) {
                def += ` DEFAULT CONVERT(VARCHAR(19), GETDATE(), 120)`;
            } else {
                def += ` DEFAULT ${defaultVal}`;
            }
        }
        
        colDefs.push(def);
    }
    
    // Add Foreign Keys explicitly at table level
    let fkDefs = [];
    // SQLite returns one row per column in a composite FK, but here they are mostly single column
    // We group by id
    const fkGroups = {};
    for (const fk of fks) {
        if (!fkGroups[fk.id]) fkGroups[fk.id] = [];
        fkGroups[fk.id].push(fk);
    }
    
    for (const fkId in fkGroups) {
        const fkCols = fkGroups[fkId];
        const fromCols = fkCols.map(f => `[${f.from}]`).join(', ');
        const toTable = fkCols[0].table;
        const toCols = fkCols.map(f => `[${f.to}]`).join(', ');
        
        const fkName = `FK_${tableName}_${toTable}_${fkCols[0].from}`;
        let fkStr = `        CONSTRAINT [${fkName}] FOREIGN KEY (${fromCols}) REFERENCES [dbo].[${toTable}] (${toCols})`;
        
        if (fkCols[0].on_delete !== 'NO ACTION' && fkCols[0].on_delete !== 'RESTRICT') {
            fkStr += ` ON DELETE ${fkCols[0].on_delete}`;
        }
        if (fkCols[0].on_update !== 'NO ACTION' && fkCols[0].on_update !== 'RESTRICT') {
            fkStr += ` ON UPDATE ${fkCols[0].on_update}`;
        }
        fkDefs.push(fkStr);
        totalFks++;
    }
    
    sqlScript += colDefs.concat(fkDefs).join(',\n');
    sqlScript += `\n    );\nEND\nGO\n\n`;
    
    // Explicit Indexes
    for (const idx of indexes) {
        // Skip auto-indexes generated by UNIQUE/PK constraints
        if (idx.origin === 'pk' || idx.origin === 'u') continue;
        
        const idxInfo = db.prepare(`PRAGMA index_info('${idx.name}')`).all();
        const idxCols = idxInfo.map(i => `[${i.name}]`).join(', ');
        const uniqueStr = idx.unique ? 'UNIQUE ' : '';
        const safeIdxName = `IX_${tableName}_${idxInfo[0].name}`;
        
        sqlScript += `IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[dbo].[${tableName}]') AND name = N'${safeIdxName}')\n`;
        sqlScript += `BEGIN\n`;
        sqlScript += `    CREATE ${uniqueStr}INDEX [${safeIdxName}] ON [dbo].[${tableName}] (${idxCols});\n`;
        sqlScript += `END\nGO\n\n`;
        totalIndexes++;
    }
}

// Generate the Validation Section
sqlScript += `
/* =========================================================================
   VALIDATION SUMMARY
   =========================================================================
   Total Tables Created: ${totalTables}
   Total Foreign Keys Generated: ${totalFks}
   Total Explicit Indexes Generated: ${totalIndexes}
   Un-translated Objects: ${missing.length === 0 ? 'None' : missing.join(', ')}
   =========================================================================
*/
`;

fs.writeFileSync('schema.sql', sqlScript);
console.log('Schema generated at schema.sql');
